title: the mimmy diaries
description: >-
  mimmy lovejoy ♡ she / they, songwriter, musician, lover of kitties & pink !! i love lots & lots of things . . . ♡
baseurl: ""
url: ""
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 7
destination: ./build
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: themimmydiaries
